### ISSUE TITLE
Repository Not Found for url: https://huggingface.co/api/models/llama-2-7b-chat.ggmlv3.q8_0.bin/revision/main. 

### ISSUE THREAD

**Issue by riyazmuthyalapati** [AIAnytime/ChatCSV-Llama2-Chatbot#3]
Please help me with below error

Repository Not Found for url: https://huggingface.co/api/models/llama-2-7b-chat.ggmlv3.q8_0.bin/revision/main. 

Please make sure you specified the correct `repo_id` and `repo_type`. If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password.

**Comment by riyazmuthyalapati** [comment]
sorry was using different quantisized version and it was not updated in the code..

**Comment by ibrahim-string** [comment]
hi @riyazmuthyalapati  did you find the reason why you were getting that error?
